# Generated by Django 5.0.4 on 2024-04-30 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0002_tags_question_tags'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tags',
            name='tag_text',
            field=models.CharField(max_length=200, unique=True),
        ),
    ]
